/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2020-12-22 06:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/style.css", Long.valueOf(1608618195720L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1608618266688L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Online quiz</title>\r\n");
      out.write("<link type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-color:#ffffff\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img,input{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("/* Style the header with a grey background and some padding */\r\n");
      out.write(".header {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #00f93f;\r\n");
      out.write("  padding: 20px 10px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("p {\r\n");
      out.write(" \r\n");
      out.write("  background-color:  #f1f1f1;\r\n");
      out.write("   padding:50px 50px 50px 50px\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Style the header links */\r\n");
      out.write(".header a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  line-height: 25px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the logo link (notice that we set the same value of line-height and font-size to prevent the header to increase when the font gets bigger */\r\n");
      out.write(".header a.logo {\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change the background color on mouse-over */\r\n");
      out.write(".header a:hover {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the active/current link*/\r\n");
      out.write(".header a.active {\r\n");
      out.write("  background-color: dodgerblue;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Float the link section to the right */\r\n");
      out.write(".header-right {\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add media queries for responsiveness - when the screen is 500px wide or less, stack the links on top of each other */\r\n");
      out.write("@media screen and (max-width: 500px) {\r\n");
      out.write("  .header a {\r\n");
      out.write("    float: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("  }\r\n");
      out.write("  .header-right {\r\n");
      out.write("    float: none;\r\n");
      out.write("  }\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Online Quiz</title>\r\n");
      out.write("<style>\r\n");
      out.write("@charset \"ISO-8859-1\";\r\n");
      out.write("body{\r\n");
      out.write("\tbackground-color:#ffffff\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img,input{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\tvertical-align:middle;\r\n");
      out.write("}\r\n");
      out.write("/* Style the header with a grey background and some padding */\r\n");
      out.write(".header {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #00f93f;\r\n");
      out.write("  padding: 20px 10px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("p {\r\n");
      out.write(" \r\n");
      out.write("  background-color:  #f1f1f1;\r\n");
      out.write("   padding:50px 50px 50px 50px\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Style the header links */\r\n");
      out.write(".header a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 12px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  line-height: 25px;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the logo link (notice that we set the same value of line-height and font-size to prevent the header to increase when the font gets bigger */\r\n");
      out.write(".header a.logo {\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change the background color on mouse-over */\r\n");
      out.write(".header a:hover {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Style the active/current link*/\r\n");
      out.write(".header a.active {\r\n");
      out.write("  background-color: dodgerblue;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Float the link section to the right */\r\n");
      out.write(".header-right {\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add media queries for responsiveness - when the screen is 500px wide or less, stack the links on top of each other */\r\n");
      out.write("@media screen and (max-width: 500px) {\r\n");
      out.write("  .header a {\r\n");
      out.write("    float: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("  }\r\n");
      out.write("  .header-right {\r\n");
      out.write("    float: none;\r\n");
      out.write("  }\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("<img src=\"F:\\zensar java training\\Onlinequiz\\WebContent\\images\\qlogo.jpg\" width=100px\">\r\n");
      out.write(" <b>Online Quiz</b> \r\n");
      out.write("  <div class=\"header-right\">\r\n");
      out.write("  <b>\r\n");
      out.write("    <a href=\"welcome.jsp\">Home</a>\r\n");
      out.write("    <a href=\"takeTest3.jsp\">Take Test</a>\r\n");
      out.write("     <a href=\"contactUs.jsp\">Contact us</a>\r\n");
      out.write("    <a href=\"about.jsp\">About</a>\r\n");
      out.write("    </b>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("    \r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<form action=\"login\" method=\"post\" >\r\n");
      out.write("<input type=\"hidden\" name=\"requestAction\" value=\"login\" />\r\n");
      out.write("     \r\n");
      out.write("    <center> <h1> Login Form </h1> </center> \r\n");
      out.write("    <br><br> \r\n");
      out.write("        <div class=\"container\">   \r\n");
      out.write("            <label>Username : </label>   \r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter Username\" name=\"username\" required> \r\n");
      out.write("            <br><br> \r\n");
      out.write("            <label>Password : </label>   \r\n");
      out.write("            <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" required>  \r\n");
      out.write("            <br><br>\r\n");
      out.write("            <button type=\"submit\">Login</button> \r\n");
      out.write("            <br>or\r\n");
      out.write("            <br><a href=\"registration.jsp\">Register Here</a>               \r\n");
      out.write("        </div>   \r\n");
      out.write("        \r\n");
      out.write("    ");
 if(request.getParameter("loginStatus")!=null){
		if(request.getParameter("loginStatus").equals("fail")){
      out.write("\r\n");
      out.write(" \t\t\t");
      out.print("Invalid Credentials" );
      out.write("\r\n");
      out.write("\t\t\t");

		}
	}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
 if(request.getParameter("logoutStatus")!=null){
		if(request.getParameter("logoutStatus").equals("yes")){
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( "You have Logout Successfully" );
      out.write("\r\n");
      out.write("\t\t\t");

		}
	}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("</center>     \r\n");
      out.write("</body>     \r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
